### ISSUE TITLE
Can we use 128*128*3 patch to train and 1024*2048*3 image to test ?

### ISSUE THREAD

**Issue by hellolingling** [varun19299/deep-atrous-guided-filter#2]
Hi  @varun19299,  can we use 128*128*3 patch to train and 1024*2048*3 image to test ?
When I use 128*128*3 patch to train a new model and inference a image with 1024*2048*3, I found the result is not correct. But if I split the image into multiple 128*128*3 path to inference, the result seems much better. 
How can I change your code to overcome the problem? 
waiting for your help!

**Comment by varun19299** [comment]
Yes, this is something we talk about in our [paper](https://arxiv.org/abs/2008.06229). Our architecture is designed to directly train on 2MP images, which attains superior results, especially on POLED measurements.
