### ISSUE TITLE
simulate checkpoints???

### ISSUE THREAD

**Issue by learningyan** [varun19299/deep-atrous-guided-filter#3]
awesome work !  
According to your paper , you  trained  a simulation network to generate simulated data. 
I want to reproduce this work on other datasets, but I cannot find the simulate pretrained checkpoints.
Cau you provide pretrained checkpoints of simulating poled or toled data ?
thanks!

**Comment by varun19299** [comment]
To clarify, I think you are asking for DAGF models which transform clean images to Glass, TOLED, POLED (which we refer to as "simulation" in our paper).

Here are the checkpoints:

| Model          | Config                                           | Checkpoint                                                                                                                  |
|----------------|--------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|
| Clean to Glass | guided_filter_l1_tanh_pixelshuffle_forward_glass | [clean2glass](https://drive.google.com/open?id=1N51EA3xg4vXq2o2OfF3_HvH2f9WBfb-6&authuser=vsundar4%40wisc.edu&usp=drive_fs) |
| Clean to POLED | guided_filter_l1_tanh_pixelshuffle_forward_poled | [clean2poled](https://drive.google.com/open?id=1HRO6I2fn0lgUL15dk3mCODEf_yBkre0b&authuser=vsundar4%40wisc.edu&usp=drive_fs) |
| Clean to TOLED | guided_filter_l1_tanh_pixelshuffle_forward_toled | [clean2toled](https://drive.google.com/open?id=18lV5VxwRf7u0v0ZNE7Xc-YCQiotSsYIz&authuser=vsundar4%40wisc.edu&usp=drive_fs) |

The code for these models can be found in the [experiments](https://github.com/varun19299/deep-atrous-guided-filter/tree/experiments) branch.

We'll add this to the README too.
